

<!DOCTYPE html>
<!--[if IE 8]><html class="no-js lt-ie9" lang="en" > <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en" > <!--<![endif]-->
<head>
  <meta charset="utf-8">
  
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <title>pygem.cad.cad_deformation &mdash; PyGeM 2.0.0 documentation</title>
  

  
  
  
  

  
  <script type="text/javascript" src="../../../_static/js/modernizr.min.js"></script>
  
    
      <script type="text/javascript" id="documentation_options" data-url_root="../../../" src="../../../_static/documentation_options.js"></script>
        <script src="../../../_static/jquery.js"></script>
        <script src="../../../_static/underscore.js"></script>
        <script src="../../../_static/doctools.js"></script>
        <script src="../../../_static/language_data.js"></script>
    
    <script type="text/javascript" src="../../../_static/js/theme.js"></script>

    

  
  <link rel="stylesheet" href="../../../_static/css/theme.css" type="text/css" />
  <link rel="stylesheet" href="../../../_static/pygments.css" type="text/css" />
  <link rel="stylesheet" href="../../../_static/graphviz.css" type="text/css" />
    <link rel="index" title="Index" href="../../../genindex.html" />
    <link rel="search" title="Search" href="../../../search.html" /> 
</head>

<body class="wy-body-for-nav">

   
  <div class="wy-grid-for-nav">
    
    <nav data-toggle="wy-nav-shift" class="wy-nav-side">
      <div class="wy-side-scroll">
        <div class="wy-side-nav-search" >
          

          
            <a href="../../../index.html" class="icon icon-home"> PyGeM
          

          
          </a>

          
            
            
              <div class="version">
                2.0.0
              </div>
            
          

          
<div role="search">
  <form id="rtd-search-form" class="wy-form" action="../../../search.html" method="get">
    <input type="text" name="q" placeholder="Search docs" />
    <input type="hidden" name="check_keywords" value="yes" />
    <input type="hidden" name="area" value="default" />
  </form>
</div>

          
        </div>

        <div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="main navigation">
          
            
            
              
            
            
              <ul>
<li class="toctree-l1"><a class="reference internal" href="../../../code.html">Code Documentation</a></li>
<li class="toctree-l1"><a class="reference internal" href="../../../tutorials.html">Tutorials</a></li>
<li class="toctree-l1"><a class="reference internal" href="../../../contact.html">Contact</a></li>
<li class="toctree-l1"><a class="reference internal" href="../../../contributing.html">How to contribute</a></li>
<li class="toctree-l1"><a class="reference internal" href="../../../LICENSE.html">License</a></li>
</ul>

            
          
        </div>
      </div>
    </nav>

    <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap">

      
      <nav class="wy-nav-top" aria-label="top navigation">
        
          <i data-toggle="wy-nav-top" class="fa fa-bars"></i>
          <a href="../../../index.html">PyGeM</a>
        
      </nav>


      <div class="wy-nav-content">
        
        <div class="rst-content">
        
          















<div role="navigation" aria-label="breadcrumbs navigation">

  <ul class="wy-breadcrumbs">
    
      <li><a href="../../../index.html">Docs</a> &raquo;</li>
        
          <li><a href="../../index.html">Module code</a> &raquo;</li>
        
      <li>pygem.cad.cad_deformation</li>
    
    
      <li class="wy-breadcrumbs-aside">
        
      </li>
    
  </ul>

  
  <hr/>
</div>
          <div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article">
           <div itemprop="articleBody">
            
  <h1>Source code for pygem.cad.cad_deformation</h1><div class="highlight"><pre>
<span></span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">Module for generic deformation for CAD file.</span>
<span class="sd">&quot;&quot;&quot;</span>
<span class="kn">import</span> <span class="nn">os</span>
<span class="kn">import</span> <span class="nn">numpy</span> <span class="k">as</span> <span class="nn">np</span>
<span class="kn">from</span> <span class="nn">itertools</span> <span class="kn">import</span> <span class="n">product</span>
<span class="kn">from</span> <span class="nn">OCC.Core.TopoDS</span> <span class="kn">import</span> <span class="p">(</span><span class="n">TopoDS_Shape</span><span class="p">,</span> <span class="n">topods_Wire</span><span class="p">,</span> <span class="n">TopoDS_Compound</span><span class="p">,</span>
                             <span class="n">topods_Face</span><span class="p">,</span> <span class="n">topods_Edge</span><span class="p">,</span> <span class="n">TopoDS_Face</span><span class="p">,</span> <span class="n">TopoDS_Wire</span><span class="p">)</span>
<span class="kn">from</span> <span class="nn">OCC.Core.BRep</span> <span class="kn">import</span> <span class="n">BRep_Builder</span>
<span class="kn">from</span> <span class="nn">OCC.Core.TopExp</span> <span class="kn">import</span> <span class="n">TopExp_Explorer</span>
<span class="kn">from</span> <span class="nn">OCC.Core.TopAbs</span> <span class="kn">import</span> <span class="p">(</span><span class="n">TopAbs_EDGE</span><span class="p">,</span> <span class="n">TopAbs_FACE</span><span class="p">,</span> <span class="n">TopAbs_WIRE</span><span class="p">)</span>
<span class="kn">from</span> <span class="nn">OCC.Core.TopTools</span> <span class="kn">import</span> <span class="n">TopTools_ListOfShape</span>
<span class="kn">from</span> <span class="nn">OCC.Core.BRepBuilderAPI</span> <span class="kn">import</span> <span class="p">(</span><span class="n">BRepBuilderAPI_MakeFace</span><span class="p">,</span>
                                     <span class="n">BRepBuilderAPI_MakeWire</span><span class="p">,</span>
                                     <span class="n">BRepBuilderAPI_MakeEdge</span><span class="p">,</span>
                                     <span class="n">BRepBuilderAPI_NurbsConvert</span><span class="p">)</span>
<span class="kn">from</span> <span class="nn">OCC.Core.BRep</span> <span class="kn">import</span> <span class="n">BRep_Tool</span><span class="p">,</span> <span class="n">BRep_Tool_Curve</span>
<span class="kn">from</span> <span class="nn">OCC.Core.Geom</span> <span class="kn">import</span> <span class="n">Geom_BSplineCurve</span><span class="p">,</span> <span class="n">Geom_BSplineSurface</span>
<span class="kn">from</span> <span class="nn">OCC.Core.GeomConvert</span> <span class="kn">import</span> <span class="p">(</span><span class="n">geomconvert_SurfaceToBSplineSurface</span><span class="p">,</span>
                                  <span class="n">geomconvert_CurveToBSplineCurve</span><span class="p">,</span>
                                  <span class="n">GeomConvert_CompCurveToBSplineCurve</span><span class="p">)</span>
<span class="kn">from</span> <span class="nn">OCC.Core.gp</span> <span class="kn">import</span> <span class="n">gp_Pnt</span>
<span class="kn">from</span> <span class="nn">OCC.Core.BRepTools</span> <span class="kn">import</span> <span class="n">breptools_OuterWire</span>
<span class="kn">from</span> <span class="nn">OCC.Core.IFSelect</span> <span class="kn">import</span> <span class="n">IFSelect_RetDone</span>
<span class="kn">from</span> <span class="nn">OCC.Core.Interface</span> <span class="kn">import</span> <span class="n">Interface_Static_SetCVal</span>
<span class="kn">from</span> <span class="nn">OCC.Core.STEPControl</span> <span class="kn">import</span> <span class="p">(</span><span class="n">STEPControl_Writer</span><span class="p">,</span> <span class="n">STEPControl_Reader</span><span class="p">,</span>
                                  <span class="n">STEPControl_AsIs</span><span class="p">)</span>
<span class="kn">from</span> <span class="nn">OCC.Core.IGESControl</span> <span class="kn">import</span> <span class="p">(</span><span class="n">IGESControl_Writer</span><span class="p">,</span> <span class="n">IGESControl_Reader</span><span class="p">,</span>
                                  <span class="n">IGESControl_Controller_Init</span><span class="p">)</span>


<div class="viewcode-block" id="CADDeformation"><a class="viewcode-back" href="../../../cad_deformation.html#pygem.cad.cad_deformation.CADDeformation">[docs]</a><span class="k">class</span> <span class="nc">CADDeformation</span><span class="p">():</span>
    <span class="sd">&quot;&quot;&quot;</span>
<span class="sd">    Base class for applting deformation to CAD geometries.</span>
<span class="sd">    </span>
<span class="sd">    :param int u_knots_to_add: the number of knots to add to the NURBS surfaces</span>
<span class="sd">        along `u` direction before the deformation. This parameter is useful</span>
<span class="sd">        whenever the gradient of the imposed deformation present spatial scales</span>
<span class="sd">        that are smaller than the local distance among the original poles of</span>
<span class="sd">        the surface/curve. Enriching the poles will allow for a more accurate</span>
<span class="sd">        application of the deformation, and might also reduce possible</span>
<span class="sd">        mismatches between bordering faces. On the orther hand, it might result</span>
<span class="sd">        in higher computational cost and bigger output files. Default is 0.</span>
<span class="sd">    :param int v_knots_to_add: the number of knots to add to the NURBS surfaces</span>
<span class="sd">        along `v` direction before the deformation. This parameter is useful</span>
<span class="sd">        whenever the gradient of the imposed deformation present spatial scales</span>
<span class="sd">        that are smaller than the local distance among the original poles of</span>
<span class="sd">        the surface/curve. Enriching the poles will allow for a more accurate</span>
<span class="sd">        application of the deformation, and might also reduce possible</span>
<span class="sd">        mismatches between bordering faces. On the orther hand, it might result</span>
<span class="sd">        in higher computational cost and bigger output files.  Default is 0.</span>
<span class="sd">    :param int t_knots_to_add: the number of knots to add to the NURBS curves</span>
<span class="sd">        before the deformation. This parameter is useful whenever the gradient</span>
<span class="sd">        of the imposed deformation present spatial scales that are smaller than</span>
<span class="sd">        the local distance among the original poles of the surface/curve.</span>
<span class="sd">        Enriching the poles will allow for a more accurate application of the</span>
<span class="sd">        deformation, and might also reduce possible mismatches between</span>
<span class="sd">        bordering faces. On the orther hand, it might result in higher</span>
<span class="sd">        computational cost and bigger output files. Default is 0.</span>
<span class="sd">    :param float tolerance: the tolerance involved in several internal</span>
<span class="sd">        operations of the procedure (joining wires in a single curve before</span>
<span class="sd">        deformation and placing new poles on curves and surfaces). Change the</span>
<span class="sd">        default value only if the input file scale is significantly different</span>
<span class="sd">        form mm, making some of the aforementioned operations fail. Default is</span>
<span class="sd">        0.0001.</span>
<span class="sd">        </span>
<span class="sd">    :cvar int u_knots_to_add: the number of knots to add to the NURBS surfaces</span>
<span class="sd">        along `u` direction before the deformation.   </span>
<span class="sd">    :cvar int v_knots_to_add: the number of knots to add to the NURBS surfaces</span>
<span class="sd">        along `v` direction before the deformation.</span>
<span class="sd">    :cvar int t_knots_to_add: the number of knots to add to the NURBS curves</span>
<span class="sd">        before the deformation.</span>
<span class="sd">    :cvar float tolerance: the tolerance involved in several internal</span>
<span class="sd">        operations of the procedure (joining wires in a single curve before</span>
<span class="sd">        deformation and placing new poles on curves and surfaces).</span>
<span class="sd">    &quot;&quot;&quot;</span>
    <span class="k">def</span> <span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span>
                 <span class="n">u_knots_to_add</span><span class="o">=</span><span class="mi">0</span><span class="p">,</span>
                 <span class="n">v_knots_to_add</span><span class="o">=</span><span class="mi">0</span><span class="p">,</span>
                 <span class="n">t_knots_to_add</span><span class="o">=</span><span class="mi">0</span><span class="p">,</span>
                 <span class="n">tolerance</span><span class="o">=</span><span class="mf">1e-4</span><span class="p">):</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">u_knots_to_add</span> <span class="o">=</span> <span class="n">u_knots_to_add</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">v_knots_to_add</span> <span class="o">=</span> <span class="n">v_knots_to_add</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">t_knots_to_add</span> <span class="o">=</span> <span class="n">t_knots_to_add</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">tolerance</span> <span class="o">=</span> <span class="n">tolerance</span>

<div class="viewcode-block" id="CADDeformation.read_shape"><a class="viewcode-back" href="../../../cad_deformation.html#pygem.cad.cad_deformation.CADDeformation.read_shape">[docs]</a>    <span class="nd">@staticmethod</span>
    <span class="k">def</span> <span class="nf">read_shape</span><span class="p">(</span><span class="n">filename</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;</span>
<span class="sd">    	Static method to load the `topoDS_Shape` from a file.</span>
<span class="sd">    	Supported extensions are: &quot;.iges&quot;, &quot;.step&quot;.</span>
<span class="sd">    	</span>
<span class="sd">    	:param str filename: the name of the file containing the geometry.</span>
<span class="sd">    	</span>
<span class="sd">    	Example:</span>
<span class="sd">    	   </span>
<span class="sd">    	   &gt;&gt;&gt; from pygem.cad import CADDeformation as CAD</span>
<span class="sd">    	   &gt;&gt;&gt; shape = CAD.read_shape(&#39;example.iges&#39;)</span>
<span class="sd">    	&quot;&quot;&quot;</span>

        <span class="n">file_extension</span> <span class="o">=</span> <span class="n">os</span><span class="o">.</span><span class="n">path</span><span class="o">.</span><span class="n">splitext</span><span class="p">(</span><span class="n">filename</span><span class="p">)[</span><span class="mi">1</span><span class="p">]</span>

        <span class="n">av_readers</span> <span class="o">=</span> <span class="p">{</span>
            <span class="s1">&#39;.step&#39;</span><span class="p">:</span> <span class="n">STEPControl_Reader</span><span class="p">,</span>
            <span class="s1">&#39;.iges&#39;</span><span class="p">:</span> <span class="n">IGESControl_Reader</span><span class="p">,</span>
        <span class="p">}</span>

        <span class="n">reader_class</span> <span class="o">=</span> <span class="n">av_readers</span><span class="o">.</span><span class="n">get</span><span class="p">(</span><span class="n">file_extension</span><span class="p">)</span>
        <span class="k">if</span> <span class="n">reader_class</span> <span class="ow">is</span> <span class="kc">None</span><span class="p">:</span>
            <span class="k">raise</span> <span class="ne">ValueError</span><span class="p">(</span><span class="s1">&#39;Unable to open the input file&#39;</span><span class="p">)</span>
        <span class="n">reader</span> <span class="o">=</span> <span class="n">reader_class</span><span class="p">()</span>

        <span class="n">return_reader</span> <span class="o">=</span> <span class="n">reader</span><span class="o">.</span><span class="n">ReadFile</span><span class="p">(</span><span class="n">filename</span><span class="p">)</span>
        <span class="c1"># check status</span>
        <span class="k">if</span> <span class="n">return_reader</span> <span class="o">==</span> <span class="n">IFSelect_RetDone</span><span class="p">:</span>
            <span class="n">return_transfer</span> <span class="o">=</span> <span class="n">reader</span><span class="o">.</span><span class="n">TransferRoots</span><span class="p">()</span>
            <span class="k">if</span> <span class="n">return_transfer</span><span class="p">:</span>
                <span class="c1"># load all shapes in one</span>
                <span class="n">shape</span> <span class="o">=</span> <span class="n">reader</span><span class="o">.</span><span class="n">OneShape</span><span class="p">()</span>
                <span class="k">return</span> <span class="n">shape</span>
            <span class="k">else</span><span class="p">:</span>
                <span class="k">raise</span> <span class="ne">RuntimeError</span><span class="p">(</span><span class="s2">&quot;Shapes not loaded.&quot;</span><span class="p">)</span>
        <span class="k">else</span><span class="p">:</span>
            <span class="k">raise</span> <span class="ne">RuntimeError</span><span class="p">(</span><span class="s2">&quot;Cannot read the file.&quot;</span><span class="p">)</span></div>

<div class="viewcode-block" id="CADDeformation.write_shape"><a class="viewcode-back" href="../../../cad_deformation.html#pygem.cad.cad_deformation.CADDeformation.write_shape">[docs]</a>    <span class="nd">@staticmethod</span>
    <span class="k">def</span> <span class="nf">write_shape</span><span class="p">(</span><span class="n">filename</span><span class="p">,</span> <span class="n">shape</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;</span>
<span class="sd">    	Static method to save a `topoDS_Shape` object to a file.</span>
<span class="sd">    	Supported extensions are: &quot;.iges&quot;, &quot;.step&quot;.</span>
<span class="sd">    	</span>
<span class="sd">    	:param str filename: the name of the file where the shape will be saved.</span>
<span class="sd">    	</span>
<span class="sd">    	Example:</span>
<span class="sd">    	   </span>
<span class="sd">    	   &gt;&gt;&gt; from pygem.cad import CADDeformation as CAD</span>
<span class="sd">    	   &gt;&gt;&gt; CAD.read_shape(&#39;example.step&#39;, my_shape)</span>
<span class="sd">    	&quot;&quot;&quot;</span>
        <span class="k">def</span> <span class="nf">write_iges</span><span class="p">(</span><span class="n">filename</span><span class="p">,</span> <span class="n">shape</span><span class="p">):</span>
            <span class="sd">&quot;&quot;&quot; IGES writer &quot;&quot;&quot;</span>
            <span class="n">IGESControl_Controller_Init</span><span class="p">()</span>
            <span class="n">writer</span> <span class="o">=</span> <span class="n">IGESControl_Writer</span><span class="p">()</span>
            <span class="n">writer</span><span class="o">.</span><span class="n">AddShape</span><span class="p">(</span><span class="n">shape</span><span class="p">)</span>
            <span class="n">writer</span><span class="o">.</span><span class="n">Write</span><span class="p">(</span><span class="n">filename</span><span class="p">)</span>

        <span class="k">def</span> <span class="nf">write_step</span><span class="p">(</span><span class="n">filename</span><span class="p">,</span> <span class="n">shape</span><span class="p">):</span>
            <span class="sd">&quot;&quot;&quot; STEP writer &quot;&quot;&quot;</span>
            <span class="n">step_writer</span> <span class="o">=</span> <span class="n">STEPControl_Writer</span><span class="p">()</span>
            <span class="c1"># Changes write schema to STEP standard AP203</span>
            <span class="c1"># It is considered the most secure standard for STEP.</span>
            <span class="c1"># *According to PythonOCC documentation (http://www.pythonocc.org/)</span>
            <span class="n">Interface_Static_SetCVal</span><span class="p">(</span><span class="s2">&quot;write.step.schema&quot;</span><span class="p">,</span> <span class="s2">&quot;AP203&quot;</span><span class="p">)</span>
            <span class="n">step_writer</span><span class="o">.</span><span class="n">Transfer</span><span class="p">(</span><span class="n">shape</span><span class="p">,</span> <span class="n">STEPControl_AsIs</span><span class="p">)</span>
            <span class="n">step_writer</span><span class="o">.</span><span class="n">Write</span><span class="p">(</span><span class="n">filename</span><span class="p">)</span>

        <span class="n">file_extension</span> <span class="o">=</span> <span class="n">os</span><span class="o">.</span><span class="n">path</span><span class="o">.</span><span class="n">splitext</span><span class="p">(</span><span class="n">filename</span><span class="p">)[</span><span class="mi">1</span><span class="p">]</span>

        <span class="n">av_writers</span> <span class="o">=</span> <span class="p">{</span>
            <span class="s1">&#39;.step&#39;</span><span class="p">:</span> <span class="n">write_step</span><span class="p">,</span>
            <span class="s1">&#39;.iges&#39;</span><span class="p">:</span> <span class="n">write_iges</span><span class="p">,</span>
        <span class="p">}</span>

        <span class="n">writer</span> <span class="o">=</span> <span class="n">av_writers</span><span class="o">.</span><span class="n">get</span><span class="p">(</span><span class="n">file_extension</span><span class="p">)</span>
        <span class="k">if</span> <span class="n">writer</span> <span class="ow">is</span> <span class="kc">None</span><span class="p">:</span>
            <span class="k">raise</span> <span class="ne">ValueError</span><span class="p">(</span><span class="s1">&#39;Unable to open the output file&#39;</span><span class="p">)</span>
        <span class="n">writer</span><span class="p">(</span><span class="n">filename</span><span class="p">,</span> <span class="n">shape</span><span class="p">)</span></div>

<div class="viewcode-block" id="CADDeformation._bspline_surface_from_face"><a class="viewcode-back" href="../../../cad_deformation.html#pygem.cad.cad_deformation.CADDeformation._bspline_surface_from_face">[docs]</a>    <span class="k">def</span> <span class="nf">_bspline_surface_from_face</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">face</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;</span>
<span class="sd">        Private method that takes a TopoDS_Face and transforms it into a</span>
<span class="sd">        Bspline_Surface.</span>
<span class="sd">        </span>
<span class="sd">    	:param TopoDS_Face face: the TopoDS_Face to be converted</span>
<span class="sd">        :rtype: Geom_BSplineSurface</span>
<span class="sd">        &quot;&quot;&quot;</span>
        <span class="k">if</span> <span class="ow">not</span> <span class="nb">isinstance</span><span class="p">(</span><span class="n">face</span><span class="p">,</span> <span class="n">TopoDS_Face</span><span class="p">):</span>
            <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s2">&quot;face must be a TopoDS_Face&quot;</span><span class="p">)</span>
        <span class="c1"># TopoDS_Face converted to Nurbs</span>
        <span class="n">nurbs_face</span> <span class="o">=</span> <span class="n">topods_Face</span><span class="p">(</span><span class="n">BRepBuilderAPI_NurbsConvert</span><span class="p">(</span><span class="n">face</span><span class="p">)</span><span class="o">.</span><span class="n">Shape</span><span class="p">())</span>
        <span class="c1"># GeomSurface obtained from Nurbs face</span>
        <span class="n">surface</span> <span class="o">=</span> <span class="n">BRep_Tool</span><span class="o">.</span><span class="n">Surface</span><span class="p">(</span><span class="n">nurbs_face</span><span class="p">)</span>
        <span class="c1"># surface is now further converted to a bspline surface</span>
        <span class="n">bspline_surface</span> <span class="o">=</span> <span class="n">geomconvert_SurfaceToBSplineSurface</span><span class="p">(</span><span class="n">surface</span><span class="p">)</span>
        <span class="k">return</span> <span class="n">bspline_surface</span></div>

<div class="viewcode-block" id="CADDeformation._bspline_curve_from_wire"><a class="viewcode-back" href="../../../cad_deformation.html#pygem.cad.cad_deformation.CADDeformation._bspline_curve_from_wire">[docs]</a>    <span class="k">def</span> <span class="nf">_bspline_curve_from_wire</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">wire</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;</span>
<span class="sd">        Private method that takes a TopoDS_Wire and transforms it into a</span>
<span class="sd">        Bspline_Curve.</span>

<span class="sd">        :param TopoDS_Wire wire: the TopoDS_Face to be converted</span>
<span class="sd">        :rtype: Geom_BSplineSurface</span>
<span class="sd">        &quot;&quot;&quot;</span>
        <span class="k">if</span> <span class="ow">not</span> <span class="nb">isinstance</span><span class="p">(</span><span class="n">wire</span><span class="p">,</span> <span class="n">TopoDS_Wire</span><span class="p">):</span>
            <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s2">&quot;wire must be a TopoDS_Wire&quot;</span><span class="p">)</span>

        <span class="c1"># joining all the wire edges in a single curve here</span>
        <span class="c1"># composite curve builder (can only join Bspline curves)</span>
        <span class="n">composite_curve_builder</span> <span class="o">=</span> <span class="n">GeomConvert_CompCurveToBSplineCurve</span><span class="p">()</span>

        <span class="c1"># iterator to edges in the TopoDS_Wire</span>
        <span class="n">edge_explorer</span> <span class="o">=</span> <span class="n">TopExp_Explorer</span><span class="p">(</span><span class="n">wire</span><span class="p">,</span> <span class="n">TopAbs_EDGE</span><span class="p">)</span>
        <span class="k">while</span> <span class="n">edge_explorer</span><span class="o">.</span><span class="n">More</span><span class="p">():</span>
            <span class="c1"># getting the edge from the iterator</span>
            <span class="n">edge</span> <span class="o">=</span> <span class="n">topods_Edge</span><span class="p">(</span><span class="n">edge_explorer</span><span class="o">.</span><span class="n">Current</span><span class="p">())</span>

            <span class="c1"># edge can be joined only if it is not degenerated (zero length)</span>
            <span class="k">if</span> <span class="n">BRep_Tool</span><span class="o">.</span><span class="n">Degenerated</span><span class="p">(</span><span class="n">edge</span><span class="p">):</span> <span class="k">continue</span>

            <span class="c1"># the edge must be converted to Nurbs edge</span>
            <span class="n">nurbs_converter</span> <span class="o">=</span> <span class="n">BRepBuilderAPI_NurbsConvert</span><span class="p">(</span><span class="n">edge</span><span class="p">)</span>
            <span class="n">nurbs_converter</span><span class="o">.</span><span class="n">Perform</span><span class="p">(</span><span class="n">edge</span><span class="p">)</span>
            <span class="n">nurbs_edge</span> <span class="o">=</span> <span class="n">topods_Edge</span><span class="p">(</span><span class="n">nurbs_converter</span><span class="o">.</span><span class="n">Shape</span><span class="p">())</span>

            <span class="c1"># here we extract the underlying curve from the Nurbs edge</span>
            <span class="n">nurbs_curve</span> <span class="o">=</span> <span class="n">BRep_Tool_Curve</span><span class="p">(</span><span class="n">nurbs_edge</span><span class="p">)[</span><span class="mi">0</span><span class="p">]</span>

            <span class="c1"># we convert the Nurbs curve to Bspline curve</span>
            <span class="n">bspline_curve</span> <span class="o">=</span> <span class="n">geomconvert_CurveToBSplineCurve</span><span class="p">(</span><span class="n">nurbs_curve</span><span class="p">)</span>

            <span class="c1"># we can now add the Bspline curve to the composite wire curve</span>
            <span class="n">composite_curve_builder</span><span class="o">.</span><span class="n">Add</span><span class="p">(</span><span class="n">bspline_curve</span><span class="p">,</span> <span class="bp">self</span><span class="o">.</span><span class="n">tolerance</span><span class="p">)</span>
            <span class="n">edge_explorer</span><span class="o">.</span><span class="n">Next</span><span class="p">()</span>

        <span class="c1"># GeomCurve obtained by the builder after edges are joined</span>
        <span class="n">comp_curve</span> <span class="o">=</span> <span class="n">composite_curve_builder</span><span class="o">.</span><span class="n">BSplineCurve</span><span class="p">()</span>
        <span class="k">return</span> <span class="n">comp_curve</span></div>

<div class="viewcode-block" id="CADDeformation._enrich_curve_knots"><a class="viewcode-back" href="../../../cad_deformation.html#pygem.cad.cad_deformation.CADDeformation._enrich_curve_knots">[docs]</a>    <span class="k">def</span> <span class="nf">_enrich_curve_knots</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">bsp_curve</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;</span>
<span class="sd">        Private method that adds `self.t_knots_to_add` poles to the passed</span>
<span class="sd">        curve.</span>
<span class="sd">        </span>
<span class="sd">        :param Geom_BSplineCurve bsp_curve: the NURBS curve to enrich</span>
<span class="sd">        &quot;&quot;&quot;</span>
        <span class="k">if</span> <span class="ow">not</span> <span class="nb">isinstance</span><span class="p">(</span><span class="n">bsp_curve</span><span class="p">,</span> <span class="n">Geom_BSplineCurve</span><span class="p">):</span>
            <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s2">&quot;bsp_curve must be a Geom_BSplineCurve&quot;</span><span class="p">)</span>
        <span class="c1"># number of knots is enriched here, if required, to</span>
        <span class="c1"># enhance precision</span>
        <span class="c1"># start parameter of composite curve</span>
        <span class="n">first_param</span> <span class="o">=</span> <span class="n">bsp_curve</span><span class="o">.</span><span class="n">FirstParameter</span><span class="p">()</span>
        <span class="c1"># end parameter of composite curve</span>
        <span class="n">last_param</span> <span class="o">=</span> <span class="n">bsp_curve</span><span class="o">.</span><span class="n">LastParameter</span><span class="p">()</span>
        <span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">t_knots_to_add</span><span class="p">):</span>
            <span class="n">bsp_curve</span><span class="o">.</span><span class="n">InsertKnot</span><span class="p">(</span><span class="n">first_param</span><span class="o">+</span> \
                           <span class="n">i</span><span class="o">*</span><span class="p">(</span><span class="n">last_param</span><span class="o">-</span><span class="n">first_param</span><span class="p">)</span><span class="o">/</span><span class="bp">self</span><span class="o">.</span><span class="n">t_knots_to_add</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> \
                           <span class="bp">self</span><span class="o">.</span><span class="n">tolerance</span><span class="p">)</span></div>

<div class="viewcode-block" id="CADDeformation._enrich_surface_knots"><a class="viewcode-back" href="../../../cad_deformation.html#pygem.cad.cad_deformation.CADDeformation._enrich_surface_knots">[docs]</a>    <span class="k">def</span> <span class="nf">_enrich_surface_knots</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">bsp_surface</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;</span>
<span class="sd">        Private method that adds `self.u_knots_to_add` and `self.v_knots_to_add`</span>
<span class="sd">        knots to the input surface `bsp_surface`, in u and v direction respectively.</span>

<span class="sd">        :param Geom_BSplineCurve bsp_surface: the NURBS surface to enrich</span>
<span class="sd">        &quot;&quot;&quot;</span>
        <span class="k">if</span> <span class="ow">not</span> <span class="nb">isinstance</span><span class="p">(</span><span class="n">bsp_surface</span><span class="p">,</span> <span class="n">Geom_BSplineSurface</span><span class="p">):</span>
            <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s2">&quot;bsp_surface must be a Geom_BSplineSurface&quot;</span><span class="p">)</span>
        <span class="c1"># we will add the prescribed amount of nodes</span>
        <span class="c1"># both along u and v parametric directions</span>

        <span class="c1"># bounds (in surface parametric space) of the surface</span>
        <span class="n">bounds</span> <span class="o">=</span> <span class="n">bsp_surface</span><span class="o">.</span><span class="n">Bounds</span><span class="p">()</span>

        <span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">u_knots_to_add</span><span class="p">):</span>
            <span class="n">bsp_surface</span><span class="o">.</span><span class="n">InsertUKnot</span><span class="p">(</span><span class="n">bounds</span><span class="p">[</span><span class="mi">0</span><span class="p">]</span><span class="o">+</span> \
                <span class="n">i</span><span class="o">*</span><span class="p">(</span><span class="n">bounds</span><span class="p">[</span><span class="mi">1</span><span class="p">]</span><span class="o">-</span><span class="n">bounds</span><span class="p">[</span><span class="mi">0</span><span class="p">])</span><span class="o">/</span><span class="bp">self</span><span class="o">.</span><span class="n">u_knots_to_add</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="bp">self</span><span class="o">.</span><span class="n">tolerance</span><span class="p">)</span>
        <span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">v_knots_to_add</span><span class="p">):</span>
            <span class="n">bsp_surface</span><span class="o">.</span><span class="n">InsertVKnot</span><span class="p">(</span><span class="n">bounds</span><span class="p">[</span><span class="mi">2</span><span class="p">]</span><span class="o">+</span> \
                <span class="n">i</span><span class="o">*</span><span class="p">(</span><span class="n">bounds</span><span class="p">[</span><span class="mi">3</span><span class="p">]</span><span class="o">-</span><span class="n">bounds</span><span class="p">[</span><span class="mi">2</span><span class="p">])</span><span class="o">/</span><span class="bp">self</span><span class="o">.</span><span class="n">v_knots_to_add</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="bp">self</span><span class="o">.</span><span class="n">tolerance</span><span class="p">)</span></div>

<div class="viewcode-block" id="CADDeformation._pole_get_components"><a class="viewcode-back" href="../../../cad_deformation.html#pygem.cad.cad_deformation.CADDeformation._pole_get_components">[docs]</a>    <span class="k">def</span> <span class="nf">_pole_get_components</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">pole</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot; Extract component from gp_Pnt &quot;&quot;&quot;</span>
        <span class="k">return</span> <span class="n">pole</span><span class="o">.</span><span class="n">X</span><span class="p">(),</span> <span class="n">pole</span><span class="o">.</span><span class="n">Y</span><span class="p">(),</span> <span class="n">pole</span><span class="o">.</span><span class="n">Z</span><span class="p">()</span></div>

<div class="viewcode-block" id="CADDeformation._pole_set_components"><a class="viewcode-back" href="../../../cad_deformation.html#pygem.cad.cad_deformation.CADDeformation._pole_set_components">[docs]</a>    <span class="k">def</span> <span class="nf">_pole_set_components</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">components</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot; Return a gp_Pnt with the passed components &quot;&quot;&quot;</span>
        <span class="k">assert</span> <span class="nb">len</span><span class="p">(</span><span class="n">components</span><span class="p">)</span> <span class="o">==</span> <span class="mi">3</span>
        <span class="k">return</span> <span class="n">gp_Pnt</span><span class="p">(</span><span class="o">*</span><span class="n">components</span><span class="p">)</span></div>

<div class="viewcode-block" id="CADDeformation._deform_bspline_curve"><a class="viewcode-back" href="../../../cad_deformation.html#pygem.cad.cad_deformation.CADDeformation._deform_bspline_curve">[docs]</a>    <span class="k">def</span> <span class="nf">_deform_bspline_curve</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">bsp_curve</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;</span>
<span class="sd">        Private method that deforms the control points of `bsp_curve` using the</span>
<span class="sd">        inherited method. All the changes are performed in place.</span>

<span class="sd">        :param Geom_Bspline_Curve bsp_curve: the curve to deform</span>
<span class="sd">        &quot;&quot;&quot;</span>
        <span class="k">if</span> <span class="ow">not</span> <span class="nb">isinstance</span><span class="p">(</span><span class="n">bsp_curve</span><span class="p">,</span> <span class="n">Geom_BSplineCurve</span><span class="p">):</span>
            <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s2">&quot;bsp_curve must be a Geom_BSplineCurve&quot;</span><span class="p">)</span>

        <span class="c1"># we first extract the poles of the curve poles number</span>
        <span class="n">n_poles</span> <span class="o">=</span> <span class="n">bsp_curve</span><span class="o">.</span><span class="n">NbPoles</span><span class="p">()</span>
        <span class="c1"># array containing the poles coordinates</span>
        <span class="n">poles_coordinates</span> <span class="o">=</span> <span class="n">np</span><span class="o">.</span><span class="n">zeros</span><span class="p">(</span><span class="n">shape</span><span class="o">=</span><span class="p">(</span><span class="n">n_poles</span><span class="p">,</span> <span class="mi">3</span><span class="p">))</span>

        <span class="c1"># cycle over the poles to get their coordinates</span>
        <span class="k">for</span> <span class="n">pole_id</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="n">n_poles</span><span class="p">):</span>
            <span class="c1"># gp_Pnt corresponding to the pole</span>
            <span class="n">pole</span> <span class="o">=</span> <span class="n">bsp_curve</span><span class="o">.</span><span class="n">Pole</span><span class="p">(</span><span class="n">pole_id</span> <span class="o">+</span> <span class="mi">1</span><span class="p">)</span>
            <span class="n">poles_coordinates</span><span class="p">[</span><span class="n">pole_id</span><span class="p">,</span> <span class="p">:]</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_pole_get_components</span><span class="p">(</span><span class="n">pole</span><span class="p">)</span>

        <span class="c1"># the new poles positions are computed through FFD</span>
        <span class="n">new_pts</span> <span class="o">=</span> <span class="nb">super</span><span class="p">()</span><span class="o">.</span><span class="fm">__call__</span><span class="p">(</span><span class="n">poles_coordinates</span><span class="p">)</span>

        <span class="c1"># the Bspline curve is now looped again to</span>
        <span class="c1"># set the poles positions  to new_points</span>
        <span class="k">for</span> <span class="n">pole_id</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="n">n_poles</span><span class="p">):</span>
            <span class="n">new_pole</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_pole_set_components</span><span class="p">(</span><span class="n">new_pts</span><span class="p">[</span><span class="n">pole_id</span><span class="p">,</span> <span class="p">:])</span>
            <span class="n">bsp_curve</span><span class="o">.</span><span class="n">SetPole</span><span class="p">(</span><span class="n">pole_id</span> <span class="o">+</span> <span class="mi">1</span><span class="p">,</span> <span class="n">new_pole</span><span class="p">)</span></div>

<div class="viewcode-block" id="CADDeformation._deform_bspline_surface"><a class="viewcode-back" href="../../../cad_deformation.html#pygem.cad.cad_deformation.CADDeformation._deform_bspline_surface">[docs]</a>    <span class="k">def</span> <span class="nf">_deform_bspline_surface</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">bsp_surface</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;</span>
<span class="sd">        Private method that deforms the control points of `surface` using the</span>
<span class="sd">        inherited method. All the changes are performed in place.</span>

<span class="sd">        :param Geom_Bspline_Surface bsp_surface: the surface to deform</span>
<span class="sd">        &quot;&quot;&quot;</span>
        <span class="k">if</span> <span class="ow">not</span> <span class="nb">isinstance</span><span class="p">(</span><span class="n">bsp_surface</span><span class="p">,</span> <span class="n">Geom_BSplineSurface</span><span class="p">):</span>
            <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s2">&quot;bsp_surface must be a Geom_BSplineSurface&quot;</span><span class="p">)</span>
        <span class="c1"># we first extract the poles of the curve</span>
        <span class="c1"># number of poles in u direction</span>
        <span class="n">n_poles_u</span> <span class="o">=</span> <span class="n">bsp_surface</span><span class="o">.</span><span class="n">NbUPoles</span><span class="p">()</span>
        <span class="c1"># number of poles in v direction</span>
        <span class="n">n_poles_v</span> <span class="o">=</span> <span class="n">bsp_surface</span><span class="o">.</span><span class="n">NbVPoles</span><span class="p">()</span>
        <span class="c1"># array which will contain the coordinates of the poles</span>
        <span class="n">poles_coordinates</span> <span class="o">=</span> <span class="n">np</span><span class="o">.</span><span class="n">zeros</span><span class="p">(</span><span class="n">shape</span><span class="o">=</span><span class="p">(</span><span class="n">n_poles_u</span> <span class="o">*</span> <span class="n">n_poles_v</span><span class="p">,</span> <span class="mi">3</span><span class="p">))</span>

        <span class="c1"># cycle over the poles to get their coordinates</span>
        <span class="n">pole_ids</span> <span class="o">=</span> <span class="n">product</span><span class="p">(</span><span class="nb">range</span><span class="p">(</span><span class="n">n_poles_u</span><span class="p">),</span> <span class="nb">range</span><span class="p">(</span><span class="n">n_poles_v</span><span class="p">))</span>
        <span class="k">for</span> <span class="n">pole_id</span><span class="p">,</span> <span class="p">(</span><span class="n">u</span><span class="p">,</span> <span class="n">v</span><span class="p">)</span> <span class="ow">in</span> <span class="nb">enumerate</span><span class="p">(</span><span class="n">pole_ids</span><span class="p">):</span>
            <span class="n">pole</span> <span class="o">=</span> <span class="n">bsp_surface</span><span class="o">.</span><span class="n">Pole</span><span class="p">(</span><span class="n">u</span> <span class="o">+</span> <span class="mi">1</span><span class="p">,</span> <span class="n">v</span> <span class="o">+</span> <span class="mi">1</span><span class="p">)</span>
            <span class="n">poles_coordinates</span><span class="p">[</span><span class="n">pole_id</span><span class="p">,</span> <span class="p">:]</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_pole_get_components</span><span class="p">(</span><span class="n">pole</span><span class="p">)</span>

        <span class="c1"># the new poles positions are computed through FFD</span>
        <span class="n">new_pts</span> <span class="o">=</span> <span class="nb">super</span><span class="p">()</span><span class="o">.</span><span class="fm">__call__</span><span class="p">(</span><span class="n">poles_coordinates</span><span class="p">)</span>

        <span class="c1"># the surface is now looped again to set the new poles positions</span>
        <span class="n">pole_ids</span> <span class="o">=</span> <span class="n">product</span><span class="p">(</span><span class="nb">range</span><span class="p">(</span><span class="n">n_poles_u</span><span class="p">),</span> <span class="nb">range</span><span class="p">(</span><span class="n">n_poles_v</span><span class="p">))</span>
        <span class="k">for</span> <span class="n">pole_id</span><span class="p">,</span> <span class="p">(</span><span class="n">u</span><span class="p">,</span> <span class="n">v</span><span class="p">)</span> <span class="ow">in</span> <span class="nb">enumerate</span><span class="p">(</span><span class="n">pole_ids</span><span class="p">):</span>
            <span class="n">new_pole</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_pole_set_components</span><span class="p">(</span><span class="n">new_pts</span><span class="p">[</span><span class="n">pole_id</span><span class="p">,</span> <span class="p">:])</span>
            <span class="n">bsp_surface</span><span class="o">.</span><span class="n">SetPole</span><span class="p">(</span><span class="n">u</span> <span class="o">+</span> <span class="mi">1</span><span class="p">,</span> <span class="n">v</span> <span class="o">+</span> <span class="mi">1</span><span class="p">,</span> <span class="n">new_pole</span><span class="p">)</span></div>

<div class="viewcode-block" id="CADDeformation.__call__"><a class="viewcode-back" href="../../../cad_deformation.html#pygem.cad.cad_deformation.CADDeformation.__call__">[docs]</a>    <span class="k">def</span> <span class="fm">__call__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">obj</span><span class="p">,</span> <span class="n">dst</span><span class="o">=</span><span class="kc">None</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;</span>
<span class="sd">        This method performs the deformation on the CAD geometry. If `obj` is a</span>
<span class="sd">        TopoDS_Shape, the method returns a TopoDS_Shape containing the deformed</span>
<span class="sd">        geometry. If `obj` is a filename, the method deforms the geometry</span>
<span class="sd">        contained in the file and writes the deformed shape to `dst` (which has</span>
<span class="sd">        to be set).</span>
<span class="sd">        </span>
<span class="sd">        :param obj: the input geometry.</span>
<span class="sd">        :type obj: str or TopoDS_Shape</span>
<span class="sd">        :param str dst: if `obj` is a string containing the input filename,</span>
<span class="sd">            `dst` refers to the file where the deformed geometry is saved.</span>
<span class="sd">        &quot;&quot;&quot;</span>
        <span class="c1"># Manage input</span>
        <span class="k">if</span> <span class="nb">isinstance</span><span class="p">(</span><span class="n">obj</span><span class="p">,</span> <span class="nb">str</span><span class="p">):</span>  <span class="c1"># if a input filename is passed</span>
            <span class="k">if</span> <span class="n">dst</span> <span class="ow">is</span> <span class="kc">None</span><span class="p">:</span>
                <span class="k">raise</span> <span class="ne">ValueError</span><span class="p">(</span>
                    <span class="s1">&#39;Source file is provided, but no destination specified&#39;</span><span class="p">)</span>
            <span class="n">shape</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_read_shape</span><span class="p">(</span><span class="n">obj</span><span class="p">)</span>
        <span class="k">elif</span> <span class="nb">isinstance</span><span class="p">(</span><span class="n">obj</span><span class="p">,</span> <span class="n">TopoDS_Shape</span><span class="p">):</span>
            <span class="n">shape</span> <span class="o">=</span> <span class="n">obj</span>
        <span class="c1"># Maybe do we need to handle also Compound?</span>
        <span class="k">else</span><span class="p">:</span>
            <span class="k">raise</span> <span class="ne">TypeError</span>

        <span class="c1">#create compound to store modified faces</span>
        <span class="n">compound_builder</span> <span class="o">=</span> <span class="n">BRep_Builder</span><span class="p">()</span>
        <span class="n">compound</span> <span class="o">=</span> <span class="n">TopoDS_Compound</span><span class="p">()</span>
        <span class="n">compound_builder</span><span class="o">.</span><span class="n">MakeCompound</span><span class="p">(</span><span class="n">compound</span><span class="p">)</span>

        <span class="c1"># cycle on the faces to get the control points</span>

        <span class="c1"># iterator to faces (TopoDS_Shape) contained in the shape</span>
        <span class="n">faces_explorer</span> <span class="o">=</span> <span class="n">TopExp_Explorer</span><span class="p">(</span><span class="n">shape</span><span class="p">,</span> <span class="n">TopAbs_FACE</span><span class="p">)</span>

        <span class="k">while</span> <span class="n">faces_explorer</span><span class="o">.</span><span class="n">More</span><span class="p">():</span>
            <span class="c1"># performing some conversions to get the right</span>
            <span class="c1"># format (BSplineSurface)</span>
            <span class="c1"># TopoDS_Face obtained from iterator</span>
            <span class="n">face</span> <span class="o">=</span> <span class="n">topods_Face</span><span class="p">(</span><span class="n">faces_explorer</span><span class="o">.</span><span class="n">Current</span><span class="p">())</span>
            <span class="c1"># performing some conversions to get the right</span>
            <span class="c1"># format (BSplineSurface)</span>
            <span class="n">bspline_surface</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_bspline_surface_from_face</span><span class="p">(</span><span class="n">face</span><span class="p">)</span>

            <span class="c1"># add the required amount of poles in u and v directions</span>
            <span class="bp">self</span><span class="o">.</span><span class="n">_enrich_surface_knots</span><span class="p">(</span><span class="n">bspline_surface</span><span class="p">)</span>

            <span class="c1"># deform the Bspline surface through FFD</span>
            <span class="bp">self</span><span class="o">.</span><span class="n">_deform_bspline_surface</span><span class="p">(</span><span class="n">bspline_surface</span><span class="p">)</span>

            <span class="c1"># through moving the control points, we now changed the SURFACE</span>
            <span class="c1"># underlying FACE we are processing. we now need to obtain the</span>
            <span class="c1"># curves (actually, the WIRES) that define the bounds of the</span>
            <span class="c1"># surface and TRIM the surface with them, to obtain the new FACE</span>

            <span class="c1">#we now start really looping on the wires</span>
            <span class="c1">#we will create a single curve joining all the edges in the wire</span>
            <span class="c1"># the curve must be a bspline curve so we need to make conversions</span>
            <span class="c1"># through all the way</span>

            <span class="c1"># list that will contain the (single) outer wire of the face</span>
            <span class="n">outer_wires</span> <span class="o">=</span> <span class="p">[]</span>
            <span class="c1"># list that will contain all the inner wires (holes) of the face</span>
            <span class="n">inner_wires</span> <span class="o">=</span> <span class="p">[]</span>
            <span class="c1"># iterator to loop over TopoDS_Wire in the original (undeformed)</span>
            <span class="c1"># face</span>
            <span class="n">wire_explorer</span> <span class="o">=</span> <span class="n">TopExp_Explorer</span><span class="p">(</span><span class="n">face</span><span class="p">,</span> <span class="n">TopAbs_WIRE</span><span class="p">)</span>
            <span class="k">while</span> <span class="n">wire_explorer</span><span class="o">.</span><span class="n">More</span><span class="p">():</span>
                <span class="c1"># wire obtained from the iterator</span>
                <span class="n">wire</span> <span class="o">=</span> <span class="n">topods_Wire</span><span class="p">(</span><span class="n">wire_explorer</span><span class="o">.</span><span class="n">Current</span><span class="p">())</span>

                <span class="c1"># getting a bpline curve joining all the edges of the wire</span>
                <span class="n">composite_curve</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_bspline_curve_from_wire</span><span class="p">(</span><span class="n">wire</span><span class="p">)</span>

                <span class="c1"># adding all the required knots to the Bspline curve</span>
                <span class="bp">self</span><span class="o">.</span><span class="n">_enrich_curve_knots</span><span class="p">(</span><span class="n">composite_curve</span><span class="p">)</span>

                <span class="c1"># deforming the Bspline curve through FFD</span>
                <span class="bp">self</span><span class="o">.</span><span class="n">_deform_bspline_curve</span><span class="p">(</span><span class="n">composite_curve</span><span class="p">)</span>

                <span class="c1"># the GeomCurve corresponding to the whole edge has now</span>
                <span class="c1"># been deformed. Now we must make it become an proper</span>
                <span class="c1"># wire</span>

                <span class="c1"># list of shapes (needed by the wire generator)</span>
                <span class="n">shapes_list</span> <span class="o">=</span> <span class="n">TopTools_ListOfShape</span><span class="p">()</span>

                <span class="c1"># edge (to be converted to wire) obtained from the modified</span>
                <span class="c1"># Bspline curve</span>
                <span class="n">modified_composite_edge</span> <span class="o">=</span> \
                    <span class="n">BRepBuilderAPI_MakeEdge</span><span class="p">(</span><span class="n">composite_curve</span><span class="p">)</span><span class="o">.</span><span class="n">Edge</span><span class="p">()</span>
                <span class="c1"># modified edge is added to shapes_list</span>
                <span class="n">shapes_list</span><span class="o">.</span><span class="n">Append</span><span class="p">(</span><span class="n">modified_composite_edge</span><span class="p">)</span>

                <span class="c1"># wire builder</span>
                <span class="n">wire_maker</span> <span class="o">=</span> <span class="n">BRepBuilderAPI_MakeWire</span><span class="p">()</span>
                <span class="n">wire_maker</span><span class="o">.</span><span class="n">Add</span><span class="p">(</span><span class="n">shapes_list</span><span class="p">)</span>
                <span class="c1"># deformed wire is finally obtained</span>
                <span class="n">modified_wire</span> <span class="o">=</span> <span class="n">wire_maker</span><span class="o">.</span><span class="n">Wire</span><span class="p">()</span>

                <span class="c1"># now, the wire can be outer or inner. we store the outer</span>
                <span class="c1"># and (possible) inner ones in different lists</span>
                <span class="c1"># this is because we first need to trim the surface</span>
                <span class="c1"># using the outer wire, and then we can trim it</span>
                <span class="c1"># with the wires corresponding to all the holes.</span>
                <span class="c1"># the wire order is important, in the trimming process</span>
                <span class="k">if</span> <span class="n">wire</span> <span class="o">==</span> <span class="n">breptools_OuterWire</span><span class="p">(</span><span class="n">face</span><span class="p">):</span>
                    <span class="n">outer_wires</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">modified_wire</span><span class="p">)</span>
                <span class="k">else</span><span class="p">:</span>
                    <span class="n">inner_wires</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">modified_wire</span><span class="p">)</span>
                <span class="n">wire_explorer</span><span class="o">.</span><span class="n">Next</span><span class="p">()</span>

            <span class="c1"># so once we finished looping on all the wires to modify them,</span>
            <span class="c1"># we first use the only outer one to trim the surface</span>
            <span class="c1"># face builder object</span>
            <span class="n">face_maker</span> <span class="o">=</span> <span class="n">BRepBuilderAPI_MakeFace</span><span class="p">(</span><span class="n">bspline_surface</span><span class="p">,</span>
                                                 <span class="n">outer_wires</span><span class="p">[</span><span class="mi">0</span><span class="p">])</span>

            <span class="c1"># and then add all other inner wires for the holes</span>
            <span class="k">for</span> <span class="n">inner_wire</span> <span class="ow">in</span> <span class="n">inner_wires</span><span class="p">:</span>
                <span class="n">face_maker</span><span class="o">.</span><span class="n">Add</span><span class="p">(</span><span class="n">inner_wire</span><span class="p">)</span>

            <span class="c1"># finally, we get our trimmed face with all its holes</span>
            <span class="n">trimmed_modified_face</span> <span class="o">=</span> <span class="n">face_maker</span><span class="o">.</span><span class="n">Face</span><span class="p">()</span>

            <span class="c1"># trimmed_modified_face is added to the modified faces compound</span>
            <span class="n">compound_builder</span><span class="o">.</span><span class="n">Add</span><span class="p">(</span><span class="n">compound</span><span class="p">,</span> <span class="n">trimmed_modified_face</span><span class="p">)</span>

            <span class="c1"># and move to the next face</span>
            <span class="n">faces_explorer</span><span class="o">.</span><span class="n">Next</span><span class="p">()</span>

        <span class="c1">## END SURFACES #################################################</span>

        <span class="k">if</span> <span class="nb">isinstance</span><span class="p">(</span><span class="n">dst</span><span class="p">,</span> <span class="nb">str</span><span class="p">):</span>  <span class="c1"># if a input filename is passed</span>
            <span class="c1"># save the shape exactly to the filename, aka `dst`</span>
            <span class="bp">self</span><span class="o">.</span><span class="n">_write_shape</span><span class="p">(</span><span class="n">dst</span><span class="p">,</span> <span class="n">compound</span><span class="p">)</span>
        <span class="k">else</span><span class="p">:</span>
            <span class="k">return</span> <span class="n">compound</span></div></div>
</pre></div>

           </div>
           
          </div>
          <footer>
  

  <hr/>

  <div role="contentinfo">
    <p>
        &copy; Copyright Copyright 2017-2020, PyGeM contributors
      <span class="lastupdated">
        Last updated on Jun 10, 2020.
      </span>

    </p>
  </div>
  Built with <a href="http://sphinx-doc.org/">Sphinx</a> using a <a href="https://github.com/rtfd/sphinx_rtd_theme">theme</a> provided by <a href="https://readthedocs.org">Read the Docs</a>. 

</footer>

        </div>
      </div>

    </section>

  </div>
  


  <script type="text/javascript">
      jQuery(function () {
          SphinxRtdTheme.Navigation.enable(true);
      });
  </script>

  
  
    
   

</body>
</html>